### ISSUE TITLE
adopt clang's diagnostics to sc

### ISSUE THREAD

**Issue by mycoboco** [mycoboco/beluga#28]
- [x] range highlight
- ~~"fix it" - correct common mistakes~~
- [x] display lines before and after macro expansion (#3)
- [x] warn using bit ops in comparison without parentheses (#51)
- [x] warn mixing `&&` and `||` without parentheses (#49)
- [x] warn `42 + b? x: y` without parentheses (#53; _decided not to implement_)

**Comment by mycoboco** [comment]
#3

**Comment by mycoboco** [comment]
#49

**Comment by mycoboco** [comment]
#51

**Comment by mycoboco** [comment]
Need to consider issuing a warning for `42 + b? x: y` or `b? x: y + 42` is really worthwhile.

**Comment by mycoboco** [comment]
#53

**Comment by mycoboco** [comment]
Decided not to support the "fix it" feature, so closed.
